#track setting and additional details for a single tracked process
type TrackSetting
{
    name: string, #user given name for the process
    img: string, #img url for this process
    process: string, #the name of the process

    totalTime: int, #total time in minutes, added during found event
    imgMadeRelative: bool #whether img field has been modified, added during found event
}

#format for tsettings.json file
#TrackSettings mapped to the unique process name
type TSettingsFile
{
    [processNames]:TrackSetting
}

#formatting for json time file.
#total time in minutes is keyed to unique process name,
#which should exist inside TSettingsFile
type TimeFile
{
    [processNames]:int
}