#track setting and additional details for a single tracked process
#May also come in an array form, which is just array of TrackSettings
type TrackSetting
{
    #original data from a data file:
    name: string, #user given name for the process
    img: string, #img url for this process

    #data appended before sending out as event
    process: string, #the name of the process
    totalTime: int, #total time in minutes, added during found event
    imgMadeRelative: bool #whether img field has been modified, added during found event
}

#format for physical tsettings.json file
#TrackSettings mapped to the unique process name
#read TrackSetting comments for which data things actually
#should go into the config file
type TSettingsFile
{
    [processNames]:TrackSetting
}

#formatting for json time file.
#total time in minutes is keyed to unique process name,
#which should exist inside TSettingsFile
type TimeFile
{
    [processNames]:int
}